[package]
name = "wlr-assets"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.26"
reqwest = { version = "0.11.18", features = ["blocking"] }
tar = "0.4.38"
bytes = "1.4.0"
path-absolutize = "3.0.14"
