[package]
name = "wlr-libpy"
version = "0.2.0"
edition = "2021"

[dependencies]
wlr-assets = { path = "../../../tools/wlr-assets", optional = true }

[features]

py311 = []
py312 = []

default = ["py311"]

build = ["dep:wlr-assets"]
py_main = []
