[package]
name = "wlr-libpy"
version = "0.1.0"
edition = "2021"

[dependencies]
wlr-assets = { path = "../../../tools/wlr-assets", optional = true }

[features]

default = []

build = ["dep:wlr-assets"]
py_main = []
