name: Build LibXML2
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
    paths:
       - ".github/**"
       - "libs/libxml2/**"
       - "libs/*"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-libxml2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 2.10.3
    uses: ./.github/workflows/reusable-build-lib.yaml
    with:
      name: "libxml2"
      version: ${{ matrix.version }}
      target-name: "libxml2"
      tag-prefix: "v"
