name: Build PHP (scheduled)
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build-php:
    strategy:
      fail-fast: false
      matrix:
        # TODO (ereslibre): the PHP cli is conditionally compiled
        # because it has the ability to open a listening socket-- only
        # supported on wasmedge --. Remove build-php-cli from here and
        # make the PHP CLI conditionally compile local server code out
        # on all versions.
        include:
          - name: ""
            suffix: ""
            build-php-cli: false
            version: master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build PHP
        run: make php/${{ matrix.name }}${{ matrix.version }}
      - name: Rename artifacts
        shell: bash
        run: |
          sudo mv php/build-output/php/${{ matrix.version }}/bin/php-cgi{${{ matrix.suffix }},-${{ matrix.version }}${{ matrix.suffix }}}.wasm
      - name: Rename artifacts
        shell: bash
        if: ${{ matrix.build-php-cli }}
        run: |
          sudo mv php/build-output/php/${{ matrix.version }}/bin/php{${{ matrix.suffix }},-${{ matrix.version }}${{ matrix.suffix }}}.wasm
      - name: Upload php-${{ matrix.version }}${{ matrix.suffix }}.wasm artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.build-php-cli }}
        with:
          name: php-${{ matrix.version }}${{ matrix.suffix }}.wasm
          path: php/build-output/php/${{ matrix.version }}/bin/php-${{ matrix.version }}${{ matrix.suffix }}.wasm
          if-no-files-found: error
      - name: Upload php-cgi-${{ matrix.version }}${{ matrix.suffix }}.wasm artifact
        uses: actions/upload-artifact@v3
        with:
          name: php-cgi-${{ matrix.version }}${{ matrix.suffix }}.wasm
          path: php/build-output/php/${{ matrix.version }}/bin/php-cgi-${{ matrix.version }}${{ matrix.suffix }}.wasm
          if-no-files-found: error
