name: Build Zlib
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - "*"
    paths:
       - ".github/**"
       - "libs/zlib/**"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-zlib:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.2.13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Zlib
        run: make libs/zlib/v${{ matrix.version }}
      - name: Upload zlib-${{ matrix.version }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlib-${{ matrix.version }}
          path: |
            build-output/zlib/v${{ matrix.version }}/include
            build-output/zlib/v${{ matrix.version }}/lib
          if-no-files-found: error
