name: Build Zlib
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
    paths:
       - ".github/**"
       - "libs/zlib/**"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-zlib:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.2.13
    uses: ./.github/workflows/reusable-build-lib.yaml
    with:
      name: "zlib"
      version: ${{ matrix.version }}
      target-name: "zlib"
      tag-prefix: "v"
