name: Build LibUuid
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
    paths:
       - ".github/**"
       - "libs/uuid/**"
       - "libs/*"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-uuid:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.0.3
    uses: ./.github/workflows/reusable-build-lib.yaml
    with:
      name: "libuuid"
      version: ${{ matrix.version }}
      target-name: "uuid"
      tag-prefix: "libuuid-"
