name: Build Lib Oniguruma
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
    paths:
       - ".github/**"
       - "libs/oniguruma/**"
       - "libs/*"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-oniguruma:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 6.9.8
    uses: ./.github/workflows/reusable-build-lib.yaml
    with:
      name: "libonig"
      version: ${{ matrix.version }}
      target-name: "oniguruma"
      tag-prefix: "v"
