name: Build Python
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
  pull_request:
jobs:
  build-python:
    strategy:
      fail-fast: false
      matrix:
        include:
          - prefix: "wasmedge-"
            suffix: "-wasmedge"
            version: 3.11.1
          - prefix: "aio-"
            suffix: "-aio"
            version: 3.11.1
          - prefix: ""
            suffix: ""
            version: 3.11.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Python
        run: make python/${{ matrix.prefix }}v${{ matrix.version }}
      - name: Rename artifacts
        shell: bash
        run: |
          sudo mv build-output/python/v${{ matrix.version }}/bin/python{${{ matrix.suffix }},-${{ matrix.version }}${{ matrix.suffix }}}.wasm
      - name: Upload python-${{ matrix.version }}.zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-${{ matrix.version }}.zip
          path: |
            build-output/python/v${{ matrix.version }}/bin/python-${{ matrix.version }}${{ matrix.suffix }}.wasm
            build-output/python/v${{ matrix.version }}/usr
          if-no-files-found: error
