name: Build LibUuid
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
    paths:
       - ".github/**"
       - "libs/uuid/**"
       - "scripts/**"
       - "Makefile*"
       - "*.sh"
  pull_request:
jobs:
  build-uuid:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1.0.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build LibUuid
        run: make libs/uuid/libuuid-${{ matrix.version }}
      - name: Upload the libuuid-${{ matrix.version }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: libuuid-${{ matrix.version }}
          path: |
            build-output/uuid/libuuid-${{ matrix.version }}/include
            build-output/uuid/libuuid-${{ matrix.version }}/lib
          if-no-files-found: error
