# Note that for this workflow to be triggered, the tag needs to be
# created of the form `python/<version>+<buildinfo>`, where <buildinfo>
# by convention is YYYYMMDD-<short-sha> (short SHA can be calculated
# with `git rev-parse --short HEAD`). An example of a tag following
# the convention that triggers automation would be
# `python/3.11.1+20221123-8dfe8b9`.
name: Release Python
on:
  push:
    tags:
      - python/*
jobs:
  build-default:
    uses: ./.github/workflows/reusable-build-runtime-flavor.yaml
    with:
      target-name: "python"
      trigger: ${{ github.event.ref }}
      flavor: ""
  build-wasmedge:
    uses: ./.github/workflows/reusable-build-runtime-flavor.yaml
    with:
      target-name: "python"
      trigger: ${{ github.event.ref }}
      flavor: "-wasmedge"
  build-aio:
    uses: ./.github/workflows/reusable-build-runtime-flavor.yaml
    with:
      target-name: "python"
      trigger: ${{ github.event.ref }}
      flavor: "-aio"
  build-aio-wasmedge:
    uses: ./.github/workflows/reusable-build-runtime-flavor.yaml
    with:
      target-name: "python"
      trigger: ${{ github.event.ref }}
      flavor: "-aio-wasmedge"
  publish:
    uses: ./.github/workflows/reusable-publish-assets.yaml
    needs: [build-default, build-wasmedge, build-aio, build-aio-wasmedge]
    with:
      target-name: "python"

