# Note that for this workflow to be triggered, the tag needs to be
# created of the form `python/<version>+<buildinfo>`, where <buildinfo>
# by convention is YYYYMMDD-<short-sha> (short SHA can be calculated
# with `git rev-parse --short HEAD`). An example of a tag following
# the convention that triggers automation would be
# `python/3.11.1+20221123-8dfe8b9`.
name: Release Python
on:
  push:
    tags:
      - python/*
jobs:
  release-python:
    strategy:
      matrix:
        include:
          - version: 3.11.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref,  format('refs/tags/python/{0}+', matrix.version))
        uses: actions/checkout@v3
      - name: Build Python
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        run: make python/v${{ matrix.version }}
      - name: Build Python Wasmedge
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        run: make python/wasmedge-v${{ matrix.version }}
      - name: Build Python AIO
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        run: make python/aio-v${{ matrix.version }}
      - name: Build Python AIO Wasmedge
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        run: make python/aio-wasmedge-v${{ matrix.version }}
      - name: Rename release artifacts
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        shell: bash
        run: |
          sudo mv build-output/python/v${{ matrix.version }}/bin/python{,-${{ matrix.version }}}.wasm
          sudo mv build-output/python/v${{ matrix.version }}-wasmedge/bin/python{,-${{ matrix.version }}-wasmedge}.wasm
          sudo mv build-output/python/v${{ matrix.version }}-aio/bin/python{,-${{ matrix.version }}}.wasm
          sudo mv build-output/python/v${{ matrix.version }}-aio-wasmedge/bin/python{,-${{ matrix.version }}-wasmedge}.wasm
      - name: Bundle Python with standard libraries
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        run: |
          tar -czvf python-${{ matrix.version }}.tar.gz --strip-components=3 \
             build-output/python/v${{ matrix.version }}/bin/python-${{ matrix.version }}.wasm \
             build-output/python/v${{ matrix.version }}/usr \
             build-output/python/v${{ matrix.version }}-wasmedge/bin/python-${{ matrix.version }}-wasmedge.wasm
      - name: Create release
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes ${{ github.ref_name }} || true
      - name: Append Python release assets
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            python-${{ matrix.version }}.tar.gz \
            build-output/python/v${{ matrix.version }}-aio/bin/python-${{ matrix.version }}.wasm \
            build-output/python/v${{ matrix.version }}-aio-wasmedge/bin/python-${{ matrix.version }}-wasmedge.wasm
      - name: Generate release assets digests
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in \
              python-${{ matrix.version }}.tar.gz \
              build-output/python/v${{ matrix.version }}-aio/bin/python-${{ matrix.version }}.wasm \
              build-output/python/v${{ matrix.version }}-aio-wasmedge/bin/python-${{ matrix.version }}-wasmedge.wasm; \
          do
            sha256sum "$asset" | sudo tee "$asset.sha256sum" > /dev/null
          done
      - name: Append release assets digests
        # Only run for the Python version specified in the git tag.
        #
        # This if could be moved to the parent `job` section when it's
        # supported by GitHub (https://github.com/community/community/discussions/37883)
        if: ${{ startsWith(github.event.ref, format('refs/tags/python/{0}+', matrix.version))}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            python-${{ matrix.version }}.tar.gz.sha256sum \
            build-output/python/v${{ matrix.version }}-aio/bin/python-${{ matrix.version }}.wasm.sha256sum \
            build-output/python/v${{ matrix.version }}-aio-wasmedge/bin/python-${{ matrix.version }}-wasmedge.wasm
