# Note: This workflow should be refactored into a custom GH action.
# This will allow us to call it in job steps and have more flexibility.
# Currently we can only call it as a separate job/ Thus we cannot populate
# its inputs from a matrix, but need to do explicit calls.
name: Build a runtime target
on:
  workflow_call:
    inputs:
      target-name:
        required: true
        type: string
      trigger:
        required: true
        type: string
      flavor:
        required: false
        type: string
        default: ""
jobs:
  release-lib:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: determineVersion
        run: |
          VERSION=$(echo ${{ inputs.trigger }} | sed 's,refs/tags/${{ inputs.target-name }}/,,g' | cut -f 1 -d \+)
          echo "value=${VERSION}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ${{ inputs.target-name }}
        run: |
          make ${{ inputs.target-name }}/v${{ steps.determineVersion.outputs.value }}${{ inputs.flavor }}
      - name: Upload ${{ inputs.target-name }}-${{ steps.determineVersion.outputs.value }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target-name }}.zip
          path: |
            build-output/*.gz
            build-output/*.wasm
            build-output/*.txt
          if-no-files-found: error