name: Release a library
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      target-name:
        required: true
        type: string
      target-prefix:
        required: true
        type: string
      trigger:
        required: true
        type: string
jobs:
  release-lib:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: determineVersion
        run: |
          VERSION=$(echo ${{ inputs.trigger }} | sed 's,refs/tags/libs/${{ inputs.target-name }}/,,g' | cut -f 1 -d \+)
          echo "value=${VERSION}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ${{ inputs.name }}
        run: make libs/${{ inputs.target-name }}/${{ inputs.target-prefix }}${{ steps.determineVersion.outputs.value }}
      - name: Package ${{ inputs.name }}-${{ steps.determineVersion.outputs.value }}.tar.gz
        run: |
          tar -cvf ${{ inputs.name }}-${{steps.determineVersion.outputs.value}}.tar \
            -C build-output/${{ inputs.target-name }}/${{ inputs.target-prefix }}${{ steps.determineVersion.outputs.value }}/ \
            include \
            lib
          gzip ${{ inputs.name }}-${{ steps.determineVersion.outputs.value }}.tar
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes ${{ github.ref_name }} || true
      - name: Append ${{ inputs.name }} release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ inputs.name }}-${{ steps.determineVersion.outputs.value }}.tar.gz
      - name: Generate release assets digests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in ${{ inputs.name }}-${{ steps.determineVersion.outputs.value }}.tar.gz; do
            sha256sum "$asset" | sudo tee "$asset.sha256sum" > /dev/null
          done
      - name: Append release assets digests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ inputs.name }}-${{ steps.determineVersion.outputs.value }}.tar.gz.sha256sum

