# Used to build an external library
# Example:
# jobs:
#   build-libs-bzip2:
#     strategy:
#       fail-fast: false
#     uses: ./.github/workflows/reusable-build-lib.yaml
#     with:
#       target: bzip2/v1.0.8

name: Build an external library
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  build-lib:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ${{ inputs.target }}
        run: make libs/${{ inputs.target }}
      - name: Upload the ${{ inputs.target }} artifact
        uses: actions/upload-artifact@v3
        with:
          path: build-output/*.gz
          if-no-files-found: error
